# Generated by Django 4.2.7 on 2023-11-18 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=512)),
                ('image', models.CharField(max_length=512)),
                ('market_cap', models.DecimalField(decimal_places=8, max_digits=18)),
                ('market_cap_change_24h', models.DecimalField(decimal_places=8, max_digits=18)),
                ('content', models.TextField()),
                ('coin1', models.CharField(max_length=512)),
                ('coin2', models.CharField(max_length=512)),
                ('coin3', models.CharField(max_length=512)),
                ('volume_24h', models.DecimalField(decimal_places=8, max_digits=18)),
            ],
        ),
    ]
