# Generated by Django 4.2.7 on 2023-11-18 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0002_categories'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='market_cap',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
        migrations.AlterField(
            model_name='categories',
            name='market_cap_change_24h',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
        migrations.AlterField(
            model_name='categories',
            name='volume_24h',
            field=models.DecimalField(decimal_places=20, max_digits=50),
        ),
    ]
