# Generated by Django 4.2.7 on 2023-11-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_customuser_balance_usercryptocurrency_paymenthistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='usercryptocurrency',
            name='quantity',
            field=models.IntegerField(default=0, max_length=4),
            preserve_default=False,
        ),
    ]
