# Generated by Django 4.2.7 on 2023-11-25 23:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0008_usercryptocurrency_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercryptocurrency',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
